require 'numbers_and_words/strategies/base'
require 'numbers_and_words/strategies/ru'
require 'numbers_and_words/strategies/en'
require 'numbers_and_words/strategies/ua'
require 'numbers_and_words/strategies/tr'
