AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'numbers_and_words.gemspec'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false
